---

- name: Install MariaDB server
  ansible.builtin.dnf:
    name: mariadb-server
    state: latest

- name: Enable MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true

- name: Update server 
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Reboot server
  ansible.builtin.reboot:
  
