---

# DEBIAN SECTION
# - name: Update cache on the Ubuntu/Debian servers
#   apt:
#     state: latest
#     update_cache: true
#
# - name: Upgrade Ubuntu/Debian servers
#   apt:
#     state: latest
#     upgrade: true
#
# - name: Clean repository cache on the Ubuntu/Debian servers
#   apt:
#     state: absent
#     autoclean: true
#     autoremove: true
#
# - name: Unconditionally reboot the Ubuntu/Debian servers
#   reboot:
#     msg: "A reboot is being kicked off by Ansible.  Please save your work."
#     pre_reboot_delay: 300

- name: Update all packages on the CentOS/Rocky servers
  dnf:
    name: "*"
    state: latest

- name: Clean up dependencies on the CentOS/Rocky servers
  dnf:
    autoremove: true

- name: Unconditionally reboot the CentOS/Rocky servers
  reboot:
    msg: "A reboot is being kicked off by Ansible.  Please save your work."
    pre_reboot_delay: 300
