---

# Change ownership of the /usr/local/bin/ directory to sysadmin:scripters
- name: Modify ownership of directory
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Change /usr/local/bin/ directory ownership to sysadmin:scripters
      ansible.builtin.file:
        path: /usr/local/bin/
        owner: sysadmin
        group: scripters
