---

- name: Check for certain installed packages on CentOS/Rocky servers 
  hosts: rhel
  #hosts: rocky,cent
  become: true
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Check for Firefox packages
      yum:
        list: firefox* 
        state: installed

    - name: Check for Brave packages
      yum:
        list: brave-browser
        state: installed

    - name: Check for Google packages
      yum:
        list: google-chrome
        state: installed

    - name: Check for OBS packages
      yum:
        list: obs-studio
        state: installed

- name: Check for certain installed packages on Ubuntu/Debian servers
  hosts: debian
  #hosts: ubuntu,lubuntu
  become: true
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Check for Firefox packages
      apt:
        name: firefox*
        state: present 

    - name: Check for Brave packages
      apt:
        name: brave-browser
        state: present 

    - name: Check for Google packages
      apt:
        name: google-chrome
        state: present 

    - name: Check for OBS packages
      apt:
        name: obs-studio
        state: present
