---

# Create a directory
- name: Create a directory
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create the /home/ansi/synced_scripts/ directory
      file:
        state: directory
        path: /home/ansi/sysnced_scripts/
        owner: ansi
        group: scripters
