---

- name: Update, upgrade and reboot virtual Debian based servers
  hosts: debian
  #hosts: ubuntu,lubuntu
  gather_facts: false
  become: true
  tasks:
    - name: Update cache on the Ubuntu/Debian servers
      apt:
        state: latest
        update_cache: true
    - name: Upgrade Ubuntu/Debian servers
      apt:
        state: latest
        upgrade: true
    - name: Clean repository cache on the Ubuntu/Debian servers
      apt:
        state: absent
        autoclean: true
        autoremove: true
    - name: Unconditionally reboot the Ubuntu/Debian servers
      reboot:
        msg: "A reboot is being kicked off by Ansible.  Please save your work."
        pre_reboot_delay: 300 
- name: Update and reboot virtual CentOS/Rocky servers
  hosts: rhel
  #hosts: rocky,cent
  gather_facts: false
  become: true
  tasks:
    - name: Update all packages on the CentOS/Rocky servers
      dnf:
        name: "*"
        state: latest
    - name: Cleanup dependencies on the CentOS/Rocky servers
      dnf:
        autoremove: true
    - name: Unconditionally reboot the CentOS/Rocky servers
      reboot:
        msg: "A reboot is being kicked off by Ansible.  Please save your work."
        pre_reboot_delay: 300
