---

- hosts: ubuntu,lubuntu,kali
  gather_facts: false
  become: true
  tasks:
    - name: Update cache on the Ubuntu/Lubuntu/Debian servers
      apt:
        state: latest
        update_cache: true
    - name: Upgrade Ubuntu/Lubuntu/Debian servers
      apt:
        state: latest
        upgrade: true
    - name: Clean repository cache on the Ubuntu/Lubuntu/Debian servers
      apt:
        state: absent
        autoclean: true
        autoremove: true
    - name: Unconditionally reboot the Ubuntu/Lubuntu/Debian servers
      reboot:
        msg: "A reboot is being kicked off by Ansible.  Please save your work."
        pre_reboot_delay: 300 
- hosts: cent
  gather_facts: false
  become: true
  tasks:
    - name: Update all packages on the CentOS server
      dnf:
        name: "*"
        state: latest
    - name: Cleanup dependencies on the CentOS server 
      dnf:
        autoremove: true
    - name: Unconditionally reboot the CentOS server
      reboot:
        msg: "A reboot is being kicked off by Ansible.  Please save your work."
        pre_reboot_delay: 300 
